theme: jekyll-theme-minimal
title: Llama Log Book
description: Logging my ideas and steps in a few subjects such as Tensor Networks, Deep Learning, RNN's and more, while not being too rigorous
email: elkabetzroy@gmail.com
